# Generated by Django 3.0.7 on 2024-02-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('userid', models.AutoField(db_column='userid', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=45, unique=True)),
                ('password', models.CharField(db_column='password', max_length=45, unique=True)),
                ('email', models.CharField(db_column='email', max_length=45, unique=True)),
                ('usertype', models.CharField(db_column='usertype', max_length=45)),
                ('name', models.CharField(db_column='name', max_length=45)),
                ('contact', models.CharField(db_column='contact', max_length=45, unique=True)),
                ('dob', models.DateField(db_column='dob')),
                ('active', models.BooleanField(db_column='active', default=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
